### ISSUE TITLE
Assignment 4-1 - Speeling

### ISSUE THREAD

**Issue by gstark** [kclauser/assignments#13]
You have noticed that your instructor is often a terrible speeler and has
trouble remembering the correct form of "initialize" in his Ruby code.

Your assignment for tonight is to make a web based dictionary powered by
Ruby and Webrick!
## Explorer Mode

Make a web server that handles three different URLs:
- [x] `/` should show all the words in the current dictionary and a link to the URL for adding new words
- [x] `/add` should show a form with a name of a word and POST this to a URL for saving words
- [x] `/save` should save the newly added word to a database (either a local array or a text file. Bonus points for using a text file that is reloaded on each request of `/`)
## Adventure Mode

Add the ability to:
- [x] Have a form on the `/` page that asks for a word to search for and POSTs to a search URL
- [x] '/search' will search for the specified word and only show the matches (bonus points for doing substring matches) and include a link back to the homepage
## Epic Mode
- [x] Find your local IP address (likely `ipconfig getifaddr en0` if you are on wifi -- or look in Network settings inside System Preferences)
- [x] Have a friend on the same local network put that ipaddress (and port number!) into their browser and add some words to your dictionary!

**Comment by kclauser** [comment]
https://github.com/kclauser/dictionary

**Comment by kclauser** [comment]
epic complete

**Comment by gstark** [comment]
Great stuff!

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/yZ3EUPGxRL5C0/200w_d.gif)
