### ISSUE TITLE
Assignment 4-3 - Speeling revisited

### ISSUE THREAD

**Issue by gstark** [kclauser/assignments#15]
Storing our words and definitions in a text file isn't the most
efficient method. Tonight we will revise our Speeling assignment
to use a richer storage format.
## Explorer Mode
- [x] Create a _new_ repository and make a copy of your ruby code.
- [x] Change the storage format from a text file to either JSON or YAML. I suggest using a file with the `.json` or `.yml` respectively.
- [x] Change your embedded HTML strings to use ERB from strings.
## Adventure Mode
- [ ] Change from ERB in strings to storing the templates in a file.
- [ ] Put the templates either in the same directory as your ruby script, or even better inside a `templates` directory.
- [ ] Your files should have an extension of `.html.erb`
## Epic Mode
- [ ] Read about [Sinatra](http://www.sinatrarb.com/intro.html) and convert your application from using WEBrick to using Sinatra. We will cover this in detail tomorrow.

**Comment by kclauser** [comment]
https://github.com/kclauser/Speeling-revisited

**Comment by gstark** [comment]
Looks great! Indentation could be cleaned up a bit, but otherwise is great.

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/L8Tn9YmDPPQsM/200w_d.gif)
