### ISSUE TITLE
Assignment 5-2 - Databasics

### ISSUE THREAD

**Issue by gstark** [kclauser/assignments#18]
Fork the repository below and follow the instructions in the included README.md

[https://github.com/tiy-tpa-ruby-q3-2015/databasics](https://github.com/tiy-tpa-ruby-q3-2015/databasics)

**Comment by kclauser** [comment]
https://github.com/kclauser/databasics

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/CMnNmzdr5jmr6/200w_d.gif)
