### ISSUE TITLE
Assignment 5-3 - ActiveRecord Powered Web Dictionary

### ISSUE THREAD

**Issue by gstark** [kclauser/assignments#19]
Our web based dictionary is awesome and we've seen how to work with text files, and then YAML/JSON. Lets power our dictionary with the power of ActiveRecord!
# Explorer Mode
- [x] If you haven't converted your web dictionary to use Sinatra, come see me and I will help you.
  - [ ] If you don't get your code converted to Sinatra, you can use your Webrick based one. However, it is time to put Webrick away and use the simpler, more powerful Sinatra.
- [x] Read all of:
  - [ ] [ActiveRecord Guide](http://guides.rubyonrails.org/active_record_basics.html)
  - [ ] [Validations Guide](http://guides.rubyonrails.org/active_record_validations.html)
- [x] Create a new repository
- [x] Using `sqlite3` command create the following table:
  - `definitions` - columns: `id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL`, `word` and `meaning`
- [x] Fill in a few (10?) definitions using `insert` statements
- [x] Update your web code to have a `Definition` class based on ActiveRecord
- [x] Reimplement the home page, add page and search page to utilize this new ActiveRecord class.
  - NOTE: Try not to write the search with `select`. See if there is an ActiveRecord way of doing it!
# Adventure Mode
- [ ] Add validation to the word and meaning and don't put the new word in the database if missing
- [ ] In case of a missing word or meaning, show an error page with a link back to the add page (rather then the existing behavior of redirecting to the home page)
# Epic Mode
- [ ] Figure out how to change the schema and the ActiveRecord classes to allow a word to have many meanings.
- [ ] Use the same existing forms, but when adding a word that already exists, create another meaning associated to this word.
- [ ] Update the homepage to show each word and all of it's meanings. Use a nice formatting.
# Over 9000 Mode
- [ ] Change your database to PostgreSQL
  - Hint: `brew install postgresql` or [postgresapp.com](postgresapp.com)
  - gem install pg
  - Figure out how to recreate the tables in postgres and configure your ActiveRecord  based app to use it

**Comment by kclauser** [comment]
https://github.com/kclauser/activerecord

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/O14RThuceJwY0/200w_d.gif)
