### ISSUE TITLE
Assignment 1-4 - Roshambo

### ISSUE THREAD

**Issue by gstark** [kclauser/assignments#5]
Every Thursday, Jason, Gavin, and Toni go for lunch. In order to determine who pays, a bout of Roshambo (aka rock-paper-scissors) is played. The problem is, programmers are lazy. Jason and Gavin can't possibly be bothered to throw their hands manually. We need you to automate this for us.

See a Roshambo match played: [![RPS FOR THE AGES!](http://img.youtube.com/vi/_eanWnL3FtM/default.jpg)](http://www.youtube.com/watch?v=_eanWnL3FtM)

Use _classes_, _hashes_, _arrays_, _strings_, etc. This assignment will likely use every bit of Ruby we have learned so far to build something greater than the sum of it's parts.
## Explorer Mode
- [x] At the start of each _match_ prompt for the name of the player
  - [x] If no name is given, the program should end
- [x] Play against the computer
  - [x] This means the computer has an "AI" that just throws _randomly_.
- [x] Play one _match_ and show the winner.
  - [x] Each throw is considered an _engagement._
  - [x] The best two of three _engagements_ is a _bout._
  - [x] The best two of three _bouts_ is a _match._
## Adventure mode
- [x] Support playing multiple games (_matches_) of Roshambo.
  - [x] After the match winner is shown:
    - [x] Show a leaderboard.
    - [x] Prompt the player to play again.
## Epic Mode

Choose one of:
- [ ] Implement a non-random AI for the computer player based on past throws based on these strategies for [advanced Roshambo AI](https://www.youtube.com/watch?v=rudzYPHuewc)

or
- [x] Keep the leaderboard between sessions
  - [x] When exiting the game, save the leaderboard to a file
    - [ ] Extra epic: use a file named `.roshambo` in the user's home directory (like our `.zshrc` config/data files)
  - [x] When starting, if a leaderboard file exists, load it and use that.
## Resources
- Entertain yourself by [reading the rules](http://www.usarps.com/rules/).
- See an unbeatable [Roshambo robot](http://www.theguardian.com/technology/video/2012/jun/27/rock-paper-scissors-robot-video)

**Comment by kclauser** [comment]
On a technical level the assignment is done, though I would like to go back and add classes and some additional polish.

https://github.com/kclauser/roshambo

**Comment by gstark** [comment]
Good stuff!

Agreed, the assignment is done but it should be in classes more, and the code could be separated into more methods, specifically for dealing with the leaderboard.

Feel free to revise and come ask questions. There is going to be lots of opportunities to work with `class`es but this is a good assignment to revisit.

**Comment by gstark** [comment]
![Awesome Work!](http://media.giphy.com/media/3ZHCdW8zxpSdq/200w_d.gif)
